close all; clear all; clc;
% FIG: Modern Climate Isotope Anomalies (OIPC)
%
%       Dervla Meegan Kumar
%       May, 2022
%

% Set Figure defaults
set(0,'DefaultAxesFontWeight','bold',...
      'DefaultAxesFontSize',12);
set(0,'DefaultTextFontWeight','bold',...
      'DefaultTextFontSize',12);
set(groot, 'DefaultAxesLineWidth',.5,...
           'DefaultAxesXColor', [0,0,0],...
           'DefaultAxesYColor', [0,0,0],...
           'DefaultAxesZColor', [0,0,0]);
       
%% Load & Process Data

% load in GPCC data and define seasonal averages
cd '/Users/dervlakumar/Google_Drive/Research/reanalysis_products/GPCC'
load gpcc_1891-2019_monthly_averages.mat
[gpccMonthly,lon,~]  = longitude_flip(gpccMonthly,lat,lon);
gpcc.lat     = double(lat); gpcc.lon = double(lon); 
gpcc.jfmRate = squeeze(sum(gpccMonthly(1:3,:,:),1))./90; 
gpcc.jasRate = squeeze(sum(gpccMonthly(7:9,:,:),1))./92;
gpcc.pjas    = squeeze(sum(gpccMonthly(7:9,:,:),1))./squeeze(sum(gpccMonthly,1)); clearvars gpccMonthly lat lon;

cd '/Users/dervlakumar/Google_Drive/Research/NAM'
filename      = 'OIPC_monthly_data.nc';
lat           = ncread(filename,'Lat');
lon           = ncread(filename,'Lon');
oipc          = permute(ncread(filename,'isotopes'),[1,3,2]);
[oipc,lon,~]  = longitude_flip(oipc,lat,lon);

% calculate anomalies
seasonalAnom  = squeeze(mean(oipc(7:9,:,:),1)-mean(oipc(1:3,:,:),1));
%gpcc.anom     = gpcc.jas-gpcc.jfm;

%% Make Fig

f1 = figure(1); clf; hold on

% define parameters
nh22pCoords   = [253.4817, 22.5183];
dsdp480Coords = [248.38, 27.85];
%nh22pCoords   = [-73.4817, 22.5183];
%dsdp480Coords = [-68.38, 27.85];
[X,Y]         = meshgrid(lon,lat);
[X2,Y2]       = meshgrid(gpcc.lon,gpcc.lat);
lonlim        = [240 280];
%lonlim        = [-120 -80];
latlim        = [5 40];

ax(1) = subplot(1,2,1); hold on; box on;
    contour_scl   = [-150:5:150];
    colorbar_scl  = [-60 60];
    title('Summer--Winter \deltaD_{precip}')
    m_proj('Miller','lon',lonlim,'lat',latlim);
    m_contourf(X,Y,seasonalAnom,...
               contour_scl,'color','none');
               colormap(ax(1),brewermap(28,'*PiYG'));
               clim(colorbar_scl);
               cbx1 = colorbar('position',[.15 0.1 0.3 0.02],...
                              'orientation','horizontal');
               set(get(cbx1,'title'),'string',{char(8240),''});
    %plot basemap
    m_coast('color','k',...
            'linewidth',.75);
    m_gshhs('fb1',...
            'color','k',...
            'linewidth',.75);
    %plot core locations
    m_scatter(nh22pCoords(:,1),nh22pCoords(:,2),...
              50,...
              'o','filled',...
              'markerfacecolor','k',...
              'markeredgecolor','k');
    m_scatter(dsdp480Coords(:,1),dsdp480Coords(:,2),...
              50,...
              'o','filled',...
              'markerfacecolor','k',...
              'markeredgecolor','k');
    %fig properties
    m_grid('xtick',[200:10:300],...
           'xaxisloc','bottom',...
           'ytick',[-10:10:50],...
           'linewidth',1,...
           'tickdir','in');
   
       
ax(2) = subplot(1,2,2); hold on; box on;
    contour_scl   = [0:.05:1];
    colorbar_scl  = [.1 .9];
    title('%JAS Precipitation')
    m_proj('Miller','lon',lonlim,'lat',latlim);
    m_contourf(X2,Y2,gpcc.pjas,...
               contour_scl,'color','none');
               colormap(ax(2),brewermap(33,'Purples'));
               clim(colorbar_scl);
               cbx2 = colorbar('position',[.6 0.1 0.3 0.02],...
                              'orientation','horizontal');
               set(get(cbx2,'title'),'string','%');
    %plot basemap
    m_coast('color','k',...
            'linewidth',.75);
    m_gshhs('fb1',...
            'color','k',...
            'linewidth',.75);
    %plot core locations
    m_scatter(nh22pCoords(:,1),nh22pCoords(:,2),...
              50,...
              'o','filled',...
              'markerfacecolor','k',...
              'markeredgecolor','k');
    m_scatter(dsdp480Coords(:,1),dsdp480Coords(:,2),...
              50,...
              'o','filled',...
              'markerfacecolor','k',...
              'markeredgecolor','k');
    %fig properties
    m_grid('xtick',[200:10:300],...
           'xaxisloc','bottom',...
           'ytick',[-10:10:50],...
           'linewidth',1,...
           'tickdir','in');
       
       
% Fig properties
set(f1,'PaperOrientation','landscape',...
       'Position',  [0, 0, 900, 500])
print('-f1','-bestfit','-vector','modern_clim_isoscape_precip_div','-dpdf')
