close all; clear all; clc;
% FIG: Leaf Wax dD time-series vs. SST time-series
%
%       Dervla Meegan Kumar
%       May, 2022
%

% Set Figure defaults
set(0,'DefaultAxesFontWeight','bold','DefaultAxesFontSize',12);
set(0,'DefaultTextFontWeight','bold','DefaultTextFontSize',12);
set(groot, 'DefaultAxesLineWidth',.5,...
           'DefaultAxesXColor', [0,0,0],...
           'DefaultAxesYColor', [0,0,0],...
           'DefaultAxesZColor', [0,0,0]);
       
%% Load & Process Data

cd '/Users/dervlakumar/Google_Drive/Research/GoC_Cores/Data/DSDP480-479'
load d480_FAMEs_11-May-2022.mat
load dsdp479_uk_sst.mat
load dsdp480_uk_sst.mat

cd '/Users/dervlakumar/Google_Drive/Research/GoC_Cores/Data/NH22P'
load nh22p_FAMEs_11-May-2022.mat
load('lr04.mat','delob')
cd '/Users/dervlakumar/Google_Drive/Research/NH22P_sst'
load nh22p_uk_sst.mat

d480.dDp_std  = nanmean(nanstd(d480.dDp,1),2);
nh22p.dDp_std = nanmean(nanstd(nh22p.dDp,1),2);

%% Make Fig
f1 = figure(1); clf;

% set bounds for SST significance
% 95% two-tailed
iupperupper = round(1000 * 0.025);
ilowerlower = round(1000 * 0.975);
% 90% two-tailed
iupper = round(1000 * 0.05);
ilower = round(1000 * 0.95);
% 68% two-tailed
iouter = round(1000 * 0.16);
iinner = round(1000 * 0.84);


modern_Mazatlan = (-29.5 + -32.4 + -33.2)/3;
col1 = [252 169 3]./255; %154 129 214
col2 = [50 99 81]./255; %98 40 235
sig1 = [172/255 203/255 243/255];     %1-sigma color (16%, 84%)
sig2 = [215/255 231/255 243/252];     %2-sigma color (5%, 95%)
mis_col = [.9 .9 .9];                        %MIS shading
xmin = 0;
xmax = 145;
dmin = 0;
dmax = 70;


% Set time boundaries for cold MIS intervals (2, 3b, 4, 5b, 5d, 6a)
mis_boundaries = [14 38 57 84 105 135;...
                  29 45 71 95 114 141;...
                  29 45 71 95 114 141;...
                  14 38 57 84 105 135];              
% make labels for MIS stages:
str = {'2','3b','4','5b','5d','6a'};
% set x position of MIS labels
text_x = [mean(mis_boundaries(1:2,1))...
          mean(mis_boundaries(1:2,2))...
          mean(mis_boundaries(1:2,3))...
          mean(mis_boundaries(1:2,4))...
          mean(mis_boundaries(1:2,5))...
          mean(mis_boundaries(1:2,6))];

% DSDP-480
subplot('position',[.1 .7 .4 .275]); hold on;
        plot(delob(:,1),delob(:,2),'-k');
        set(gca,...
            'Ylim',[3 5.1],...
            'YTick',[3:.5:5],...
            'ydir','reverse',...
            'ycolor','k');  
        ylabel(['\delta^{18}O (',char(8240),')'])
        set(gca,...
            'XLim',[xmin xmax],...
            'XTick',[xmin:20:xmax],...
            'XTickLabel',[xmin:20:xmax],...
            'xminortick','on');
        xlabel('AGE (ka)')

subplot('position',[.1 .375 .4 .275]); hold on;
        shadedErrorBar(d480.depth(1:114,:),nanmean(d480.dDp(1:114,:),2),repmat(d480.dDp_std,114,1),...
        'lineprops',{'-','color',col1},...
        'transparent',1,'patchsaturation',.4);
        shadedErrorBar(d480.depth(115:end,:),nanmean(d480.dDp(115:end,:),2),repmat(d480.dDp_std,29,1),...
        'lineprops',{'-','color',col1},...
        'transparent',1,'patchsaturation',.4);
        plot(d480.depth(1:114,:),nanmean(d480.dDp(1:114,:),2),'-','linewidth',1.5,'color',col1);
        plot(d480.depth(115:end,:),nanmean(d480.dDp(115:end,:),2),'-','linewidth',1.5,'color',col1);
        set(gca,...
            'Ylim',[-80 -35],...
            'ycolor','k');
        ylabel(['\delta D_{precip} (',char(8240),')'])
        set(gca,...
            'XLim',[dmin dmax],...
            'XTick',[dmin:10:dmax],...
            'XTickLabel',[dmin:10:dmax],...
            'xminortick','on');
        xlabel('DEPTH (m)')
        
subplot('position',[.1 .05 .4 .275]); hold on;
        ymax = 34;
        ymin = 15;
        sortedd480 = sort(d480_BSPLINE_out.ens,2);
        Hseb = shadedErrorBar3(uk480.depth(1:62,:),uk480.SST(1:62,:),...
                               sortedd480(1:62,[ilowerlower iupperupper])',...
                               sortedd480(1:62,[iinner iouter])','k'); hold on;
                               set(Hseb.mainLine,'Color','none','linewidth',1.2);
                               set(Hseb.patch1,'facecolor',sig2,'edgecolor','none');
                               set(Hseb.patch2,'facecolor',sig1,'edgecolor','none');
        Hseb = shadedErrorBar3(uk480.depth(63:end,:),uk480.SST(63:end,:),...
                               sortedd480(63:end,[ilowerlower iupperupper])',...
                               sortedd480(63:end,[iinner iouter])','k'); hold on;
                               set(Hseb.mainLine,'Color','none','linewidth',1.2);
                               set(Hseb.patch1,'facecolor',sig2,'edgecolor','none');
                               set(Hseb.patch2,'facecolor',sig1,'edgecolor','none');
        plot(uk480.depth(1:62,:),uk480.SST(1:62,:),'-k','linewidth',1);
        plot(uk480.depth(63:end,:),uk480.SST(63:end,:),'-k','linewidth',1);
        set(gca,...
            'YLim',[ymin ymax],...
            'YTick',[20:5:30],...
            'YTickLabel',[20:5:30],...
            'yminortick','on',...
            'YColor','k',...
            'linewidth',1)
        ylabel('SST (°C)') 
        set(gca,...
            'XLim',[dmin dmax],...
            'XTick',[dmin:10:dmax],...
            'XTickLabel',[dmin:10:dmax],...
            'xminortick','on');
        xlabel('DEPTH (m)')
        text(2,2.9,'DSDP-480','Fontsize',16);

        
% NH22P    
subplot('position',[.575 .7 .4 .275]); hold on;
        ymax = 5.1;
        ymin = 3;
        y1 = repmat([0; 0; 5.1; 5.1],1,6);
        patch(mis_boundaries,...
            y1,...
            mis_col,...
            'edgecolor','none',...
            'handlevisibility','off');
        text(text_x,...
             repmat(ymin+.1,1,6),...
             str,...
             'HorizontalAlignment','center');
        plot(delob(:,1),delob(:,2),'-k');
        set(gca,...
            'Ylim',[3 5.1],...
            'YTick',[3:.5:5],...
            'ydir','reverse',...
            'ycolor','k');  
        ylabel(['\delta^{18}O (',char(8240),')'])
        set(gca,...
            'XLim',[xmin xmax],...
            'XTick',[xmin:20:xmax],...
            'XTickLabel',[xmin:20:xmax],...
            'xminortick','on');
        xlabel('AGE (ka)')
    
subplot('position',[.575 .375 .4 .275]); hold on;
        ymax = -35;
        ymin = -80;
        y1 = repmat([ymin; ymin; ymax; ymax],1,6); % set y limits for MIS shading
        patch(mis_boundaries(:,:),...
            y1(:,:),...
            mis_col,...
            'edgecolor','none',...
            'handlevisibility','off');
        shadedErrorBar(nh22p.age,nanmean(nh22p.dDp,2),repmat(nh22p.dDp_std,size(nh22p.age,1),1),...
        'lineprops',{'-','color',col1},...
        'transparent',1,'patchsaturation',.4);
        plot(nh22p.age,nanmean(nh22p.dDp,2),'-','linewidth',1.5,'color',col1);
        set(gca,...
            'Ylim',[ymin ymax],...
            'ycolor','k');
        ylabel(['\delta D_{precip} (',char(8240),')'])
        set(gca,...
            'XLim',[xmin xmax],...
            'XTick',[xmin:20:xmax],...
            'XTickLabel',[xmin:20:xmax],...
            'xminortick','on');
        xlabel('AGE (ka)')
        
subplot('position',[.575 .05 .4 .275]); hold on;
        ymax = 34;
        ymin = 15;
        y1 = repmat([ymin; ymin; ymax; ymax],1,6); % set y limits for MIS shading
        patch(mis_boundaries(:,:),...
            y1(:,:),...
            mis_col,...
            'edgecolor','none',...
            'handlevisibility','off');
        sortednh22p = sort(byspln_nh22p.ens,2);
        Hseb = shadedErrorBar3(age_nh22p,byspln_nh22p.SST(:,2),...
                               sortednh22p(:,[ilowerlower iupperupper])',...
                               sortednh22p(:,[iinner iouter])','k'); hold on;
                               set(Hseb.mainLine,'Color','none','linewidth',1.2);
                               set(Hseb.patch1,'facecolor',sig2,'edgecolor','none');
                               set(Hseb.patch2,'facecolor',sig1,'edgecolor','none');
        plot(age_nh22p,byspln_nh22p.SST(:,2),'-k','linewidth',1);
        set(gca,...
            'YLim',[ymin ymax],...
            'YTick',[20:5:30],...
            'YTickLabel',[20:5:30],...
            'yminortick','on',...
            'YColor','k',...
            'linewidth',1)
        ylabel('SST (°C)') 
        set(gca,...
            'XLim',[xmin xmax],...
            'XTick',[xmin:20:xmax],...
            'XTickLabel',[xmin:20:xmax],...
            'xminortick','on');
        xlabel('AGE (ka)')
        

% Fig properties
set(f1,'PaperOrientation','portrait');
set(f1, 'Position',  [0, 0, 800, 1000])
cd '/Users/dervlakumar/Google_Drive/Research/NAM'
%print('-f1','-bestfit','-painters','dDp_time-series','-dpdf')